# Generated by Django 4.2.7 on 2025-08-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(choices=[('nizami', 'Nizami'), ('sabail', 'Sabail'), ('yasamal', 'Yasamal'), ('binagadi', 'Binagadi'), ('khazar', 'Khazar'), ('sabunchu', 'Sabunchu'), ('surakhani', 'Surakhani'), ('khatai', 'Khatai'), ('narimanov', 'Narimanov'), ('nasimi', 'Nasimi'), ('pirallahi', 'Pirallahi'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username without @', max_length=100)),
                ('price_range', models.CharField(choices=[('budget', '$ - Budget'), ('moderate', '$$ - Moderate'), ('expensive', '$$$ - Expensive'), ('luxury', '$$$$ - Luxury')], default='moderate', max_length=10)),
                ('opening_hours', models.TextField(help_text='Opening hours information')),
                ('features', models.TextField(blank=True, help_text='Special features, amenities, etc.')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/images/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for main image', max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating out of 5', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured places')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified business')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('pub', 'Pub'), ('club', 'Club'), ('activity', 'Activity Place'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('museum', 'Museum'), ('park', 'Park'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(default='fas fa-map-marker-alt', max_length=50)),
                ('color', models.CharField(default='#5DD3BE', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Place Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.placecategory'),
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('place', 'reviewer_email')},
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category', 'district'], name='places_plac_categor_0dbb57_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_active', 'is_featured'], name='places_plac_is_acti_735ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['rating'], name='places_plac_rating_1aa694_idx'),
        ),
    ]
