# Generated by Django 4.2.7 on 2025-08-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration_hours', models.PositiveIntegerField(help_text='Duration in hours')),
                ('location_name', models.CharField(help_text='Name of the venue/location', max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(choices=[('nizami', 'Nizami'), ('sabail', 'Sabail'), ('yasamal', 'Yasamal'), ('binagadi', 'Binagadi'), ('khazar', 'Xəzər'), ('sabunchu', 'Sabunçu'), ('surakhani', 'Suraxanı'), ('khatai', 'Xətai'), ('narimanov', 'Nərimanov'), ('nasimi', 'Nəsimi'), ('pirallahi', 'Pirallahı'), ('other', 'Digər')], default='other', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_participants', models.PositiveIntegerField()),
                ('min_participants', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in AZN', max_digits=8)),
                ('is_free', models.BooleanField(default=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Başlanğıc'), ('intermediate', 'Orta'), ('advanced', 'İrəliləmiş'), ('expert', 'Ekspert')], default='beginner', max_length=20)),
                ('requirements', models.TextField(blank=True, help_text='What participants need to bring or know')),
                ('what_included', models.TextField(blank=True, help_text="What's included in the activity")),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for main image', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Qaralama'), ('published', 'Yayımlanmış'), ('cancelled', 'Ləğv edilmiş'), ('completed', 'Tamamlanmış')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured activities')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('sports', 'İdman'), ('culture', 'Mədəniyyət'), ('nature', 'Təbiət'), ('art', 'Sənət'), ('food', 'Yemək'), ('education', 'Təhsil'), ('social', 'Sosial'), ('entertainment', 'Əyləncə'), ('technology', 'Texnologiya'), ('music', 'Musiqi'), ('photography', 'Fotoqrafiya'), ('travel', 'Səyahət'), ('business', 'Biznes'), ('health', 'Sağlamlıq'), ('other', 'Digər')], default='other', max_length=20)),
                ('icon', models.CharField(default='fas fa-calendar-alt', max_length=50)),
                ('color', models.CharField(default='#5DD3BE', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('approved', 'Təsdiqlənmiş'), ('rejected', 'Rədd edilmiş'), ('cancelled', 'Ləğv edilmiş')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message from participant to organizer')),
                ('join_requested_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('organizer_response', models.TextField(blank=True, help_text='Response from organizer')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-join_requested_at'],
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activities.activitycomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.activity')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='activities.activityparticipant')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('activity', 'reviewer')},
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'district'], name='activities__categor_63eaad_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'start_date'], name='activities__status_01c74a_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_featured'], name='activities__is_feat_dfade3_idx'),
        ),
    ]
