# Generated by Django 4.2.7 on 2025-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender'),
        ('activities', '0002_activitymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allowed_genders',
            field=models.JSONField(blank=True, default=list, help_text='Allowed genders for participants'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age requirement', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age requirement', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_languages',
            field=models.ManyToManyField(blank=True, help_text='Languages participants must know', to='accounts.language'),
        ),
    ]
