# Generated by Django 5.2.5 on 2025-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_allowed_genders_activity_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
