# Generated by Django 5.2.5 on 2025-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitycategory_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dress_code',
            field=models.CharField(blank=True, help_text='Dress code for the activity', max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='gender_balance_required',
            field=models.BooleanField(default=False, help_text='Require balanced gender participation'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_unlimited_participants',
            field=models.BooleanField(default=False, help_text='No limit on participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in hours (auto-calculated)', null=True),
        ),
    ]
