# Generated by Django 5.2.4 on 2025-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_dress_code_activity_gender_balance_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional - defaults to 3 hours after start', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for cards', max_length=300),
        ),
    ]
