# Generated by Django 4.2.7 on 2025-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blogcategory_blogtag_blogpost_blogposttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Kişi'), ('female', 'Qadın'), ('other', 'Digər'), ('prefer_not_to_say', 'Deməyi üstün tutmuram')], max_length=20, null=True),
        ),
    ]
