# Generated by Django 5.0.14 on 2025-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='registration', max_length=15),
        ),
    ]
