# Generated by Django 5.2.4 on 2025-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpverification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.CharField(choices=[('general', 'General/Popular'), ('beauty', 'Beauty & Fashion'), ('lifestyle', 'Lifestyle & Home'), ('sports', 'Sports & Fitness'), ('arts', 'Arts & Culture'), ('food', 'Food & Dining'), ('travel', 'Travel & Adventure'), ('tech', 'Technology'), ('music', 'Music'), ('nature', 'Nature & Outdoors'), ('education', 'Education & Learning'), ('health', 'Health & Wellness'), ('social', 'Social & Volunteering')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='interest',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Show in general/popular section'),
        ),
    ]
