# Generated by Django 5.2.4 on 2025-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_interest_category_interest_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image for interest', null=True, upload_to='interest_icons/'),
        ),
    ]
