# Generated by Django 5.2.4 on 2025-11-29 13:07

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_interests(apps, schema_editor):
    """Create InterestCategory records and update Interest records"""
    InterestCategory = apps.get_model('accounts', 'InterestCategory')
    Interest = apps.get_model('accounts', 'Interest')
    
    # Category definitions with Azerbaijani names
    categories_data = [
        {'code': 'general', 'name': 'Ümumi / Populyar', 'icon': 'fas fa-star', 'order': 0},
        {'code': 'sports', 'name': 'İdman & Fitnes', 'icon': 'fas fa-running', 'order': 1},
        {'code': 'music', 'name': 'Musiqi', 'icon': 'fas fa-music', 'order': 2},
        {'code': 'arts', 'name': 'Sənət & Mədəniyyət', 'icon': 'fas fa-palette', 'order': 3},
        {'code': 'food', 'name': 'Yemək & Qəlyanaltı', 'icon': 'fas fa-utensils', 'order': 4},
        {'code': 'travel', 'name': 'Səyahət & Macəra', 'icon': 'fas fa-plane', 'order': 5},
        {'code': 'nature', 'name': 'Təbiət & Açıq Hava', 'icon': 'fas fa-leaf', 'order': 6},
        {'code': 'tech', 'name': 'Texnologiya', 'icon': 'fas fa-laptop-code', 'order': 7},
        {'code': 'beauty', 'name': 'Gözəllik & Moda', 'icon': 'fas fa-gem', 'order': 8},
        {'code': 'lifestyle', 'name': 'Həyat Tərzi', 'icon': 'fas fa-home', 'order': 9},
        {'code': 'education', 'name': 'Təhsil & Öyrənmə', 'icon': 'fas fa-graduation-cap', 'order': 10},
        {'code': 'health', 'name': 'Sağlamlıq', 'icon': 'fas fa-heartbeat', 'order': 11},
        {'code': 'social', 'name': 'Sosial & Könüllülük', 'icon': 'fas fa-hands-helping', 'order': 12},
    ]
    
    # Create categories and build a mapping
    category_map = {}
    for cat_data in categories_data:
        category, created = InterestCategory.objects.get_or_create(
            code=cat_data['code'],
            defaults={
                'name': cat_data['name'],
                'icon': cat_data['icon'],
                'order': cat_data['order'],
                'is_active': True
            }
        )
        category_map[cat_data['code']] = category
    
    # Update existing interests to link to the new categories
    for interest in Interest.objects.all():
        old_category = interest.old_category
        if old_category and old_category in category_map:
            interest.category = category_map[old_category]
            interest.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration - copy category code back to old_category"""
    Interest = apps.get_model('accounts', 'Interest')
    
    for interest in Interest.objects.all():
        if interest.category:
            interest.old_category = interest.category.code
            interest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_interest_icon_image'),
    ]

    operations = [
        # Step 1: Create the InterestCategory model
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'İdman & Fitnes')", max_length=100, unique=True)),
                ('code', models.SlugField(help_text="Unique code (e.g., 'sports')", unique=True)),
                ('icon', models.CharField(default='fas fa-star', help_text="Font Awesome icon class (e.g., 'fas fa-running')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category in registration')),
            ],
            options={
                'verbose_name': 'Interest Category',
                'verbose_name_plural': 'Interest Categories',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Step 2: Rename the old category field temporarily
        migrations.RenameField(
            model_name='interest',
            old_name='category',
            new_name='old_category',
        ),
        
        # Step 3: Add the new category ForeignKey field (nullable)
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(
                blank=True, 
                help_text='Category this interest belongs to', 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='interests', 
                to='accounts.interestcategory'
            ),
        ),
        
        # Step 4: Run data migration to create categories and update interests
        migrations.RunPython(create_categories_and_migrate_interests, reverse_migration),
        
        # Step 5: Remove the old category field
        migrations.RemoveField(
            model_name='interest',
            name='old_category',
        ),
    ]
