# Generated by Django 5.2.5 on 2025-12-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_interest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_signup',
            field=models.BooleanField(default=False, help_text='True if user registered via Google OAuth'),
        ),
    ]
