# Generated by Django 5.2.5 on 2025-12-07 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_google_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('friend_request', 'Dostluq sorğusu'), ('friend_accepted', 'Dostluq qəbul edildi'), ('friend_rejected', 'Dostluq rədd edildi'), ('friend_new_activity', 'Dost yeni aktivitə yaratdı'), ('activity_join_request', 'Aktivitəyə qoşulma sorğusu'), ('activity_participant_joined', 'Yeni iştirakçı qoşuldu'), ('activity_participant_left', 'İştirakçı ayrıldı'), ('activity_comment', 'Aktivitəyə yeni şərh'), ('activity_update', 'Aktivitə yeniləndi'), ('activity_cancelled', 'Aktivitə ləğv edildi'), ('activity_reminder', 'Aktivitə xatırlatması'), ('activity_starting_soon', 'Aktivitə tezliklə başlayır'), ('new_activity_nearby', 'Yaxınlıqda yeni aktivitə'), ('new_activity_interest', 'Maraqlarınıza uyğun aktivitə'), ('new_message', 'Yeni mesaj'), ('system', 'Sistem bildirişi'), ('promotional', 'Reklam')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_activity_id', models.IntegerField(blank=True, null=True)),
                ('related_friendship_id', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('is_read', models.BooleanField(default=False)),
                ('is_pushed', models.BooleanField(default=False, help_text='Was push notification sent')),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_requests', models.BooleanField(default=True, help_text='Yeni dostluq sorğuları')),
                ('friend_request_accepted', models.BooleanField(default=True, help_text='Dostluq sorğusu qəbul edildi')),
                ('friend_new_activity', models.BooleanField(default=True, help_text='Dostlarım yeni aktivitə yaratdı')),
                ('activity_join_request', models.BooleanField(default=True, help_text='Aktivitə qoşulma sorğusu')),
                ('activity_participant_left', models.BooleanField(default=True, help_text='İştirakçı aktivitəni tərk etdi')),
                ('activity_comment', models.BooleanField(default=True, help_text='Aktivitəyə yeni şərh')),
                ('activity_update', models.BooleanField(default=True, help_text='Qatıldığım aktivitədə dəyişiklik')),
                ('activity_cancelled', models.BooleanField(default=True, help_text='Aktivitə ləğv edildi')),
                ('activity_reminder', models.BooleanField(default=True, help_text='Aktivitə xatırlatması (1 gün əvvəl)')),
                ('new_activities_nearby', models.BooleanField(default=True, help_text='Yaxınlıqda yeni aktivitələr')),
                ('new_activities_interests', models.BooleanField(default=True, help_text='Maraqlarıma uyğun yeni aktivitələr')),
                ('new_message', models.BooleanField(default=True, help_text='Yeni mesaj bildirişi')),
                ('system_updates', models.BooleanField(default=True, help_text='Sistem yenilikləri')),
                ('promotional', models.BooleanField(default=False, help_text='Reklam və təkliflər')),
                ('push_enabled', models.BooleanField(default=True, help_text='Push bildirişlərini aktivləşdir')),
                ('email_enabled', models.BooleanField(default=False, help_text='Email bildirişlərini aktivləşdir')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Səssiz saatları aktivləşdir')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Səssiz saatların başlanğıcı')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='Səssiz saatların sonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
