# Generated by Django 5.2.5 on 2025-12-08 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_conversation_directmessage'),
        ('activities', '0006_make_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Activity Group Chat',
                'verbose_name_plural': 'Activity Group Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('sent', 'Göndərildi'), ('delivered', 'Çatdırıldı')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.activitygroupchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Group Message',
                'verbose_name_plural': 'Activity Group Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
