from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.utils import timezone
from activities.models import ActivityCategory, Activity
from datetime import timedelta
import random
import urllib.request
import os
from django.conf import settings
from django.core.files import File

User = get_user_model()


class Command(BaseCommand):
    help = 'Create sample activities data for demonstration'

    def download_image(self, url, filepath):
        """Download image from URL and save to filepath"""
        try:
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            urllib.request.urlretrieve(url, filepath)
            return True
        except Exception as e:
            self.stdout.write(self.style.WARNING(f'Could not download image from {url}: {e}'))
            return False

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Creating sample activities data...'))

        # Get or create a superuser as organizer
        try:
            organizer = User.objects.filter(is_superuser=True).first()
            if not organizer:
                organizer = User.objects.create_superuser(
                    phone='+994501234567',
                    first_name='Acteezer',
                    last_name='Admin',
                    email='admin@acteezer.az',
                    password='admin123'
                )
                self.stdout.write(f'Created organizer: {organizer.get_full_name()}')
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Error creating organizer: {e}'))
            return

        # Create categories
        categories_data = [
            {'name': 'İdman', 'category_type': 'sports', 'icon': 'fas fa-running', 'color': '#ef4444'},
            {'name': 'Mədəniyyət', 'category_type': 'culture', 'icon': 'fas fa-theater-masks', 'color': '#8b5cf6'},
            {'name': 'Təbiət', 'category_type': 'nature', 'icon': 'fas fa-tree', 'color': '#22c55e'},
            {'name': 'Sənət', 'category_type': 'art', 'icon': 'fas fa-palette', 'color': '#f59e0b'},
            {'name': 'Yemək', 'category_type': 'food', 'icon': 'fas fa-utensils', 'color': '#ec4899'},
            {'name': 'Təhsil', 'category_type': 'education', 'icon': 'fas fa-graduation-cap', 'color': '#3b82f6'},
            {'name': 'Sosial', 'category_type': 'social', 'icon': 'fas fa-users', 'color': '#06b6d4'},
            {'name': 'Əyləncə', 'category_type': 'entertainment', 'icon': 'fas fa-gamepad', 'color': '#a855f7'},
            {'name': 'Musiqi', 'category_type': 'music', 'icon': 'fas fa-music', 'color': '#10b981'},
            {'name': 'Fotoqrafiya', 'category_type': 'photography', 'icon': 'fas fa-camera', 'color': '#6366f1'},
            {'name': 'Texnologiya', 'category_type': 'technology', 'icon': 'fas fa-laptop-code', 'color': '#06b6d4'},
            {'name': 'Səyahət', 'category_type': 'travel', 'icon': 'fas fa-plane', 'color': '#3b82f6'},
            {'name': 'Biznes', 'category_type': 'business', 'icon': 'fas fa-briefcase', 'color': '#6366f1'},
            {'name': 'Sağlamlıq', 'category_type': 'health', 'icon': 'fas fa-heartbeat', 'color': '#ef4444'},
        ]

        categories = {}
        for cat_data in categories_data:
            category, created = ActivityCategory.objects.get_or_create(
                name=cat_data['name'],
                defaults=cat_data
            )
            categories[cat_data['category_type']] = category
            if created:
                self.stdout.write(f'Created category: {category.name}')

        # Sample activities data - 50+ activities in Azerbaijani
        base_date = timezone.now() + timedelta(days=1)
        activities_data = [
            {
                'title': 'Şahdağ Milli Parkı Gəzintisi',
                'category': 'nature',
                'short_description': 'Təbiətin qoynunda gözəl gün keçirmək və yeni dostlar tapmaq üçün',
                'description': 'Şahdağ Milli Parkında təşkil olunan bu gəzinti təbiət sevərləri üçün ideal imkandır. Gəzinti zamanı gözəl mənzərələr, təmiz hava və yeni dostluqlar sizi gözləyir.',
                'location_name': 'Şahdağ Milli Parkı',
                'address': 'Quba-Qusar yolu, Şahdağ',
                'district': 'other',
                'max_participants': 12,
                'min_participants': 4,
                'duration_hours': 8,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 25.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=1, hours=8),
                'end_date': base_date + timedelta(days=1, hours=16),
                'requirements': 'Rahat geyim, idman ayaqqabısı, su və yemək',
                'what_included': 'Nəqliyyat, bələdçi xidməti, ilk yardım dəsti',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800'
            },
            {
                'title': 'Milli Mətbəx Festivalı',
                'category': 'food',
                'short_description': 'Azərbaycan mətbəxinin ləzzətlərini dadmaq və öyrənmək',
                'description': 'Bakı Bulvarında keçiriləcək bu festival zamanı Azərbaycan mətbəxinin ən dadlı yeməklərini dadacaq və hazırlanma sirlərini öyrənəcəksiniz.',
                'location_name': 'Bakı Bulvarı',
                'address': 'Dənizkənarı Milli Park, Bakı Bulvarı',
                'district': 'sabail',
                'max_participants': 20,
                'min_participants': 5,
                'duration_hours': 4,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=3, hours=14),
                'end_date': base_date + timedelta(days=3, hours=18),
                'requirements': 'Heç nə lazım deyil',
                'what_included': 'Bütün yeməklər, içkilər və reseptlər',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800'
            },
            {
                'title': 'İçəri Şəhər Fotoqrafiya Turu',
                'category': 'photography',
                'short_description': 'Tarixi İçəri Şəhərin gözəl küncələrini fotoqraflamaq',
                'description': 'Professional fotoqrafçı ilə birlikdə tarixi İçəri Şəhərin ən gözəl yerlərini kəşf edəcək və fotoqrafiya bacarığınızı inkişaf etdirəcəksiniz.',
                'location_name': 'İçəri Şəhər',
                'address': 'Şirvanşahlar Sarayı, İçəri Şəhər',
                'district': 'sabail',
                'max_participants': 10,
                'min_participants': 3,
                'duration_hours': 3,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 20.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=5, hours=10),
                'end_date': base_date + timedelta(days=5, hours=13),
                'requirements': 'Fotoqraf (telefon da olar), rahat ayaqqabı',
                'what_included': 'Professional bələdçi, fotoqrafiya məsləhətləri',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1518843025960-d60217f226f5?w=800'
            },
            {
                'title': 'Səhər Yoga Seansı',
                'category': 'sports',
                'short_description': 'Gün ərzində enerjili olmaq üçün səhər yoga məşğələsi',
                'description': 'Dənizkənarı Parkda təşkil olunan səhər yoga seansı ilə gününüzə enerjili başlayın. Təcrübəli instruktor rəhbərliyində yoga hərekatları öyrənəcəksiniz.',
                'location_name': 'Dənizkənarı Park',
                'address': 'Dənizkənarı Milli Park',
                'district': 'sabail',
                'max_participants': 15,
                'min_participants': 5,
                'duration_hours': 1,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=2, hours=7),
                'end_date': base_date + timedelta(days=2, hours=8),
                'requirements': 'Yoga matı, rahat geyim',
                'what_included': 'Yoga matı (lazım olsa), su',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800'
            },
            {
                'title': 'Kitab Klubu Görüşü',
                'category': 'education',
                'short_description': 'Oxuduğumuz kitabları müzakirə edib yeni dostlar tapırıq',
                'description': 'Bu ay "Arşın mal alan" əsərini oxuduq və indi birlikdə müzakirə edəcəyik. Kitab sevərlər üçün ideal imkan.',
                'location_name': 'Mərkəzi Kitabxana',
                'address': 'M.F.Axundov adına Azərbaycan Milli Kitabxanası',
                'district': 'sabail',
                'max_participants': 12,
                'min_participants': 4,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=7, hours=18),
                'end_date': base_date + timedelta(days=7, hours=20),
                'requirements': 'Kitabı oxumuş olmaq',
                'what_included': 'Çay, şirniyyat',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800'
            },
            {
                'title': 'Jazz Konsert Gecəsi',
                'category': 'music',
                'short_description': 'Canlı jazz musiqisi dinləyərək keyfiyyətli vaxt keçirmək',
                'description': 'Bakının məşhur jazz klubunda keçiriləcək bu gecədə yerli və beynəlxalq jazz musiqiçilərinin möhtəşəm çıxışları olacaq.',
                'location_name': 'Baku Jazz Club',
                'address': 'Fountain Square, Jazz Club',
                'district': 'sabail',
                'max_participants': 20,
                'min_participants': 8,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 30.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=10, hours=20),
                'end_date': base_date + timedelta(days=10, hours=23),
                'requirements': 'Heç nə',
                'what_included': 'Canlı musiqi, bir içki',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'
            },
            {
                'title': 'Bowling Gecəsi',
                'category': 'entertainment',
                'short_description': 'Dostlarla əyləncəli bowling oyunu',
                'description': 'Həftə sonu dostlarla birlikdə bowling oynayaraq əyləncəli vaxt keçirin. Hər səviyyədən iştirakçı qəbul olunur.',
                'location_name': 'Bowling City',
                'address': 'Gənclik Mall, Babək prospekti',
                'district': 'binagadi',
                'max_participants': 16,
                'min_participants': 6,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 12.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=6, hours=19),
                'end_date': base_date + timedelta(days=6, hours=21),
                'requirements': 'Rahat geyim',
                'what_included': 'Bowling oyunu, ayaqqabı kirayəsi',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800'
            },
            {
                'title': 'İncəsənət Atölyəsi',
                'category': 'art',
                'short_description': 'Rəsm və əl işlərini öyrənmək üçün yaradıcı atölye',
                'description': 'Yaradıcı atölyədə rəsm çəkməyi və müxtəlif əl işlərini öyrənəcək, öz sənət əsərinizi yaradacaqsınız.',
                'location_name': 'Sənət Mərkəzi',
                'address': 'Yasamal rayonu, Sənət Mərkəzi',
                'district': 'yasamal',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 18.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=8, hours=15),
                'end_date': base_date + timedelta(days=8, hours=18),
                'requirements': 'Heç nə',
                'what_included': 'Bütün materiallar, çay',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1513364776144-60967b0fccf1?w=800'
            },
            {
                'title': 'Futbol Oyunu',
                'category': 'sports',
                'short_description': 'Dostlarla birlikdə futbol oynayaraq idman edin',
                'description': 'Həftə sonu futbol meydanında birlikdə futbol oynayacağıq. Hər səviyyədən oyunçu qəbul olunur.',
                'location_name': 'İdman Kompleksi',
                'address': 'Nizami rayonu, İdman Kompleksi',
                'district': 'nizami',
                'max_participants': 22,
                'min_participants': 10,
                'duration_hours': 2,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 8.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=2, hours=16),
                'end_date': base_date + timedelta(days=2, hours=18),
                'requirements': 'İdman ayaqqabısı, rahat geyim',
                'what_included': 'Meydan, top',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800'
            },
            {
                'title': 'Muzey Sərgisi',
                'category': 'culture',
                'short_description': 'Azərbaycan tarixi və mədəniyyətini kəşf edin',
                'description': 'Azərbaycan Tarix Muzeyində təşkil olunan ekskursiya. Tarixi eksponatlar və mədəni əsərlərlə tanış olacağıq.',
                'location_name': 'Azərbaycan Tarix Muzeyi',
                'address': 'İstiqlaliyyət küçəsi, Bakı',
                'district': 'sabail',
                'max_participants': 15,
                'min_participants': 5,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 5.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=4, hours=11),
                'end_date': base_date + timedelta(days=4, hours=13),
                'requirements': 'Heç nə',
                'what_included': 'Bilet, bələdçi',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'
            },
            {
                'title': 'Qəbələ Turu',
                'category': 'travel',
                'short_description': 'Qəbələnin gözəl təbiətini kəşf edin',
                'description': 'Qəbələ şəhərinə günlük tur. Gözəl mənzərələr, təmiz hava və əsl təbiət sizi gözləyir.',
                'location_name': 'Qəbələ',
                'address': 'Qəbələ şəhəri',
                'district': 'other',
                'max_participants': 18,
                'min_participants': 8,
                'duration_hours': 10,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 35.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=12, hours=7),
                'end_date': base_date + timedelta(days=12, hours=17),
                'requirements': 'Rahat geyim, fotoqraf',
                'what_included': 'Nəqliyyat, bələdçi, nahar',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800'
            },
            {
                'title': 'Python Proqramlaşdırma Kursu',
                'category': 'technology',
                'short_description': 'Python proqramlaşdırma dilini sıfırdan öyrənin',
                'description': 'Başlanğıc səviyyədən Python proqramlaşdırma dilini öyrənəcəksiniz. Praktiki tapşırıqlar və layihələr.',
                'location_name': 'Texnologiya Mərkəzi',
                'address': 'Nəsimi rayonu, Texnologiya Mərkəzi',
                'district': 'nasimi',
                'max_participants': 20,
                'min_participants': 8,
                'duration_hours': 4,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 40.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=5, hours=14),
                'end_date': base_date + timedelta(days=5, hours=18),
                'requirements': 'Laptop, əsas kompüter bilikləri',
                'what_included': 'Materiallar, çay, şirniyyat',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800'
            },
            {
                'title': 'Biznes Görüşü',
                'category': 'business',
                'short_description': 'Biznesmenlərlə görüş və networking',
                'description': 'Uğurlu biznesmenlərlə görüş, təcrübə paylaşımı və networking imkanı.',
                'location_name': 'Biznes Mərkəzi',
                'address': 'Nərimanov rayonu, Biznes Mərkəzi',
                'district': 'narimanov',
                'max_participants': 25,
                'min_participants': 10,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=9, hours=18),
                'end_date': base_date + timedelta(days=9, hours=21),
                'requirements': 'Biznes kartı',
                'what_included': 'Çay, qəlyanaltı, networking',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800'
            },
            {
                'title': 'Meditasiya Seansı',
                'category': 'health',
                'short_description': 'Daxili sülhü tapmaq üçün meditasiya',
                'description': 'Stressdən azad olmaq və daxili sülhü tapmaq üçün meditasiya seansı. Təcrübəli mentor rəhbərliyi.',
                'location_name': 'Sağlamlıq Mərkəzi',
                'address': 'Yasamal rayonu, Sağlamlıq Mərkəzi',
                'district': 'yasamal',
                'max_participants': 12,
                'min_participants': 4,
                'duration_hours': 1.5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=3, hours=19),
                'end_date': base_date + timedelta(days=3, hours=20, minutes=30),
                'requirements': 'Rahat geyim',
                'what_included': 'Meditasiya matı, aromaterapiya',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800'
            },
            {
                'title': 'Xalça Toxunması Atölyəsi',
                'category': 'art',
                'short_description': 'Azərbaycan xalçası toxunması sənətini öyrənin',
                'description': 'Ənənəvi Azərbaycan xalça toxunması sənətini öyrənəcəksiniz. Müəllimlərin rəhbərliyi ilə.',
                'location_name': 'Xalça Muzeyi',
                'address': 'Mikayıl Useynov prospekti, Xalça Muzeyi',
                'district': 'yasamal',
                'max_participants': 8,
                'min_participants': 4,
                'duration_hours': 4,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 25.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=11, hours=10),
                'end_date': base_date + timedelta(days=11, hours=14),
                'requirements': 'Heç nə',
                'what_included': 'Bütün materiallar, çay',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800'
            },
            {
                'title': 'Səhər Qaçışı',
                'category': 'sports',
                'short_description': 'Səhər qaçışı ilə günə başlayın',
                'description': 'Dənizkənarı parkda təşkil olunan səhər qaçışı. Enerji ilə dolu gün üçün ideal başlanğıc.',
                'location_name': 'Dənizkənarı Park',
                'address': 'Dənizkənarı Milli Park',
                'district': 'sabail',
                'max_participants': 20,
                'min_participants': 5,
                'duration_hours': 1,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=4, hours=7),
                'end_date': base_date + timedelta(days=4, hours=8),
                'requirements': 'İdman ayaqqabısı, rahat geyim',
                'what_included': 'Su',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800'
            },
            {
                'title': 'Qədim Şəhər Gəzintisi',
                'category': 'culture',
                'short_description': 'İçəri Şəhərin tarixi yerlərini kəşf edin',
                'description': 'Bakının qədim məhəllələrini, sarayları və məscidləri ziyarət edəcəyik. Tarixi bələdçi ilə.',
                'location_name': 'İçəri Şəhər',
                'address': 'İçəri Şəhər, Bakı',
                'district': 'sabail',
                'max_participants': 15,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 12.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=6, hours=10),
                'end_date': base_date + timedelta(days=6, hours=13),
                'requirements': 'Rahat ayaqqabı',
                'what_included': 'Bələdçi, giriş biletləri',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'
            },
            {
                'title': 'Azərbaycan Xalq Musiqisi Konserti',
                'category': 'music',
                'short_description': 'Ənənəvi Azərbaycan musiqisini dinləyin',
                'description': 'Azərbaycan xalq musiqisinin gözəl nümunələrini canlı dinləyəcəksiniz. Tar, kamança və digər alətlər.',
                'location_name': 'Musiqi Akademiyası',
                'address': 'Nizami prospekti, Musiqi Akademiyası',
                'district': 'nizami',
                'max_participants': 30,
                'min_participants': 10,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 18.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=13, hours=19),
                'end_date': base_date + timedelta(days=13, hours=21),
                'requirements': 'Heç nə',
                'what_included': 'Konsert, çay',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'
            },
            {
                'title': 'Balıq Tutma Turu',
                'category': 'nature',
                'short_description': 'Xəzər dənizində balıq tutma təcrübəsi',
                'description': 'Xəzər dənizində balıq tutma təcrübəsi. Təcrübəli balıqçı ilə birlikdə.',
                'location_name': 'Xəzər Sahili',
                'address': 'Bilgəh, Xəzər sahili',
                'district': 'khazar',
                'max_participants': 10,
                'min_participants': 4,
                'duration_hours': 5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 30.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=14, hours=6),
                'end_date': base_date + timedelta(days=14, hours=11),
                'requirements': 'Rahat geyim',
                'what_included': 'Balıq tutma avadanlığı, nahar',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800'
            },
            {
                'title': 'İngilis Dili Dərsləri',
                'category': 'education',
                'short_description': 'İngilis dilini praktiki öyrənin',
                'description': 'Kommunikativ metodla İngilis dilini öyrənəcəksiniz. Praktiki dialoqlar və tapşırıqlar.',
                'location_name': 'Dil Mərkəzi',
                'address': 'Nəsimi rayonu, Dil Mərkəzi',
                'district': 'nasimi',
                'max_participants': 12,
                'min_participants': 6,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 22.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=7, hours=16),
                'end_date': base_date + timedelta(days=7, hours=18),
                'requirements': 'Dəftər, qələm',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800'
            },
            {
                'title': 'Piknik və Oyunlar',
                'category': 'social',
                'short_description': 'Təbiətdə piknik və əyləncəli oyunlar',
                'description': 'Göy Göl ətrafında piknik və müxtəlif əyləncəli oyunlar. Yeni dostlar və əyləncəli vaxt.',
                'location_name': 'Göy Göl',
                'address': 'Göy Göl Milli Parkı',
                'district': 'other',
                'max_participants': 20,
                'min_participants': 8,
                'duration_hours': 6,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=15, hours=9),
                'end_date': base_date + timedelta(days=15, hours=15),
                'requirements': 'Rahat geyim',
                'what_included': 'Nəqliyyat, yemək, içkilər',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'
            },
            {
                'title': 'Rəsm Kursu',
                'category': 'art',
                'short_description': 'Rəsm çəkməyi öyrənin',
                'description': 'Akvarel və yağlı boya ilə rəsm çəkməyi öyrənəcəksiniz. Professional rəssam rəhbərliyi.',
                'location_name': 'Rəssamlıq Akademiyası',
                'address': 'Nizami prospekti, Rəssamlıq Akademiyası',
                'district': 'nizami',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=8, hours=14),
                'end_date': base_date + timedelta(days=8, hours=17),
                'requirements': 'Heç nə',
                'what_included': 'Bütün materiallar',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800'
            },
            {
                'title': 'Velosiped Turu',
                'category': 'sports',
                'short_description': 'Bakı ətrafında velosiped turu',
                'description': 'Bakının gözəl yerlərini velosipedlə kəşf edin. Sağlamlıq və əyləncə bir arada.',
                'location_name': 'Dənizkənarı Park',
                'address': 'Dənizkənarı Milli Park',
                'district': 'sabail',
                'max_participants': 15,
                'min_participants': 6,
                'duration_hours': 2,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 15.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=10, hours=16),
                'end_date': base_date + timedelta(days=10, hours=18),
                'requirements': 'İdman geyimi',
                'what_included': 'Velosiped kirayəsi, su',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800'
            },
            {
                'title': 'Pizza Hazırlama Atölyəsi',
                'category': 'food',
                'short_description': 'Əsl italyan pizzası hazırlamağı öyrənin',
                'description': 'Professional aşpaz rəhbərliyində əsl italyan pizzası hazırlamağı öyrənəcəksiniz.',
                'location_name': 'Aşpazlıq Məktəbi',
                'address': 'Yasamal rayonu, Aşpazlıq Məktəbi',
                'district': 'yasamal',
                'max_participants': 12,
                'min_participants': 6,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 25.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=9, hours=15),
                'end_date': base_date + timedelta(days=9, hours=18),
                'requirements': 'Apron',
                'what_included': 'Bütün materiallar, pizza',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800'
            },
            {
                'title': 'Gecə Fotoqrafiya Turu',
                'category': 'photography',
                'short_description': 'Bakının gecə görünüşünü fotoqraflayın',
                'description': 'Bakının gecə görünüşünü fotoqraflamaq üçün xüsusi tur. Gecə fotoqrafiyası texnikaları.',
                'location_name': 'Flame Towers',
                'address': 'Flame Towers, Bakı',
                'district': 'sabail',
                'max_participants': 10,
                'min_participants': 4,
                'duration_hours': 3,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 22.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=11, hours=20),
                'end_date': base_date + timedelta(days=11, hours=23),
                'requirements': 'Fotoqraf, tripod',
                'what_included': 'Bələdçi, məsləhətlər',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1492144534655-ae79c2c03457?w=800'
            },
            {
                'title': 'Tennis Oyunu',
                'category': 'sports',
                'short_description': 'Tennis meydanında oyun və məşq',
                'description': 'Tennis meydanında oyun və məşq. Hər səviyyədən oyunçu qəbul olunur.',
                'location_name': 'Tennis Klubu',
                'address': 'Nərimanov rayonu, Tennis Klubu',
                'district': 'narimanov',
                'max_participants': 8,
                'min_participants': 4,
                'duration_hours': 2,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 18.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=12, hours=17),
                'end_date': base_date + timedelta(days=12, hours=19),
                'requirements': 'İdman geyimi',
                'what_included': 'Meydan, raket və top',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800'
            },
            {
                'title': 'Teatr Səhnəsi',
                'category': 'culture',
                'short_description': 'Azərbaycan teatr əsərini izləyin',
                'description': 'Azərbaycan Dövlət Akademik Dram Teatrında klassik əsərin tamaşasını izləyəcəksiniz.',
                'location_name': 'Dram Teatrı',
                'address': 'Nizami prospekti, Dram Teatrı',
                'district': 'nizami',
                'max_participants': 25,
                'min_participants': 10,
                'duration_hours': 2.5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=16, hours=19),
                'end_date': base_date + timedelta(days=16, hours=21, minutes=30),
                'requirements': 'Heç nə',
                'what_included': 'Bilet',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800'
            },
            {
                'title': 'Web Dizayn Kursu',
                'category': 'technology',
                'short_description': 'Web dizaynın əsaslarını öyrənin',
                'description': 'HTML, CSS və JavaScript əsaslarını öyrənəcəksiniz. Responsive dizayn prinsipləri.',
                'location_name': 'Texnologiya Akademiyası',
                'address': 'Nəsimi rayonu, Texnologiya Akademiyası',
                'district': 'nasimi',
                'max_participants': 15,
                'min_participants': 8,
                'duration_hours': 4,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 35.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=6, hours=14),
                'end_date': base_date + timedelta(days=6, hours=18),
                'requirements': 'Laptop',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800'
            },
            {
                'title': 'Çimərlik Günü',
                'category': 'nature',
                'short_description': 'Xəzər dənizində çimərlikdə istirahət',
                'description': 'Xəzər dənizinin sahilində çimərlikdə istirahət. Güvənli çimərlik, təmiz su.',
                'location_name': 'Çimərlik',
                'address': 'Bilgəh çimərliyi',
                'district': 'khazar',
                'max_participants': 20,
                'min_participants': 8,
                'duration_hours': 6,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=17, hours=10),
                'end_date': base_date + timedelta(days=17, hours=16),
                'requirements': 'Çimərlik geyimi, havlu',
                'what_included': 'Çimərlik biletləri, soyuducu',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'
            },
            {
                'title': 'Sağlamlıq Seminarı',
                'category': 'health',
                'short_description': 'Sağlam həyat tərzi haqqında məlumat',
                'description': 'Sağlam həyat tərzi, düzgün qidalanma və məşq haqqında seminar. Həkim rəhbərliyi.',
                'location_name': 'Sağlamlıq Mərkəzi',
                'address': 'Yasamal rayonu, Sağlamlıq Mərkəzi',
                'district': 'yasamal',
                'max_participants': 30,
                'min_participants': 10,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=4, hours=18),
                'end_date': base_date + timedelta(days=4, hours=20),
                'requirements': 'Heç nə',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800'
            },
            {
                'title': 'Səyahət Fotoqrafiyası',
                'category': 'photography',
                'short_description': 'Səyahət zamanı gözəl şəkillər çəkin',
                'description': 'Səyahət fotoqrafiyasının sirlərini öyrənin. Gözəl mənzərələri necə çəkmək olar.',
                'location_name': 'Yanar Dağ',
                'address': 'Yanar Dağ, Abşeron',
                'district': 'other',
                'max_participants': 12,
                'min_participants': 5,
                'duration_hours': 4,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 25.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=18, hours=14),
                'end_date': base_date + timedelta(days=18, hours=18),
                'requirements': 'Fotoqraf',
                'what_included': 'Nəqliyyat, bələdçi',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800'
            },
            {
                'title': 'Astarta Turu',
                'category': 'travel',
                'short_description': 'Astarta qəsəbəsinə günlük tur',
                'description': 'Astarta qəsəbəsinə günlük tur. Gözəl təbiət və tarixi yerlər.',
                'location_name': 'Astarta',
                'address': 'Astarta qəsəbəsi',
                'district': 'other',
                'max_participants': 15,
                'min_participants': 6,
                'duration_hours': 8,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 28.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=19, hours=8),
                'end_date': base_date + timedelta(days=19, hours=16),
                'requirements': 'Rahat geyim',
                'what_included': 'Nəqliyyat, bələdçi, nahar',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800'
            },
            {
                'title': 'Karting',
                'category': 'entertainment',
                'short_description': 'Karting idmanı ilə adrenalin yaşayın',
                'description': 'Karting meydanında sürət və adrenalin. Hər səviyyədən iştirakçı.',
                'location_name': 'Karting Klubu',
                'address': 'Binagadi rayonu, Karting Klubu',
                'district': 'binagadi',
                'max_participants': 12,
                'min_participants': 4,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 35.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=13, hours=15),
                'end_date': base_date + timedelta(days=13, hours=17),
                'requirements': '18+ yaş',
                'what_included': 'Kart, kask, təlimat',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1558980664-1dbcfcd4c1fe?w=800'
            },
            {
                'title': 'Gitar Dərsləri',
                'category': 'music',
                'short_description': 'Gitar çalmağı öyrənin',
                'description': 'Başlanğıc səviyyədən gitar çalmağı öyrənəcəksiniz. Təcrübəli müəllim rəhbərliyi.',
                'location_name': 'Musiqi Məktəbi',
                'address': 'Nizami rayonu, Musiqi Məktəbi',
                'district': 'nizami',
                'max_participants': 8,
                'min_participants': 4,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 30.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=14, hours=16),
                'end_date': base_date + timedelta(days=14, hours=18),
                'requirements': 'Öz gitarınız (və ya kirayə)',
                'what_included': 'Materiallar',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800'
            },
            {
                'title': 'Şəkil Çəkmə Workshop',
                'category': 'photography',
                'short_description': 'Portret və mənzərə fotoqrafiyası',
                'description': 'Portret və mənzərə fotoqrafiyasının texnikalarını öyrənin. Praktiki iş.',
                'location_name': 'Fotoqrafiya Mərkəzi',
                'address': 'Yasamal rayonu, Fotoqrafiya Mərkəzi',
                'district': 'yasamal',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 28.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=15, hours=14),
                'end_date': base_date + timedelta(days=15, hours=17),
                'requirements': 'Fotoqraf',
                'what_included': 'Studio, avadanlıq',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800'
            },
            {
                'title': 'Qolf Oyunu',
                'category': 'sports',
                'short_description': 'Qolf meydanında oyun',
                'description': 'Qolf meydanında oyun və məşq. Yeni başlayanlar üçün ideal.',
                'location_name': 'Qolf Klubu',
                'address': 'Xəzər rayonu, Qolf Klubu',
                'district': 'khazar',
                'max_participants': 10,
                'min_participants': 4,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 40.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=16, hours=14),
                'end_date': base_date + timedelta(days=16, hours=17),
                'requirements': 'İdman geyimi',
                'what_included': 'Avadanlıq, təlimat',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800'
            },
            {
                'title': 'Sushi Hazırlama',
                'category': 'food',
                'short_description': 'Yapon mətbəxindən sushi hazırlamağı öyrənin',
                'description': 'Professional aşpaz rəhbərliyində sushi hazırlamağı öyrənəcəksiniz.',
                'location_name': 'Aşpazlıq Məktəbi',
                'address': 'Yasamal rayonu, Aşpazlıq Məktəbi',
                'district': 'yasamal',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 30.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=10, hours=15),
                'end_date': base_date + timedelta(days=10, hours=18),
                'requirements': 'Apron',
                'what_included': 'Bütün materiallar, sushi',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800'
            },
            {
                'title': 'Startup Görüşü',
                'category': 'business',
                'short_description': 'Startup sahibkarları ilə görüş',
                'description': 'Uğurlu startup sahibkarları ilə görüş, təcrübə paylaşımı və networking.',
                'location_name': 'Startup Mərkəzi',
                'address': 'Nərimanov rayonu, Startup Mərkəzi',
                'district': 'narimanov',
                'max_participants': 25,
                'min_participants': 10,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 25.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=20, hours=18),
                'end_date': base_date + timedelta(days=20, hours=21),
                'requirements': 'Biznes kartı',
                'what_included': 'Çay, qəlyanaltı',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800'
            },
            {
                'title': 'Plivanlıq Dərsləri',
                'category': 'sports',
                'short_description': 'Üzgüçülük texnikalarını öyrənin',
                'description': 'Təcrübəli məşqçi rəhbərliyində üzgüçülük texnikalarını öyrənəcəksiniz.',
                'location_name': 'Üzgüçülük Kompleksi',
                'address': 'Nərimanov rayonu, Üzgüçülük Kompleksi',
                'district': 'narimanov',
                'max_participants': 12,
                'min_participants': 6,
                'duration_hours': 1.5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=11, hours=19),
                'end_date': base_date + timedelta(days=11, hours=20, minutes=30),
                'requirements': 'Üzgüçülük geyimi',
                'what_included': 'Hovuz, məşqçi',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800'
            },
            {
                'title': 'Dil Dəyişkəni',
                'category': 'social',
                'short_description': 'Müxtəlif dilləri öyrənmək üçün görüş',
                'description': 'Müxtəlif dilləri öyrənmək istəyən insanların görüşü. Dil təcrübəsi və yeni dostlar.',
                'location_name': 'Kafe',
                'address': 'Nizami rayonu, Kafe',
                'district': 'nizami',
                'max_participants': 20,
                'min_participants': 8,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 10.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=8, hours=18),
                'end_date': base_date + timedelta(days=8, hours=20),
                'requirements': 'Heç nə',
                'what_included': 'Çay, kofe',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800'
            },
            {
                'title': 'Dağ Gəzintisi',
                'category': 'nature',
                'short_description': 'Böyük Qafqaz dağlarında gəzinti',
                'description': 'Böyük Qafqaz dağlarında gəzinti. Gözəl mənzərələr və təmiz hava.',
                'location_name': 'Şahdağ',
                'address': 'Şahdağ dağ kompleksi',
                'district': 'other',
                'max_participants': 12,
                'min_participants': 5,
                'duration_hours': 6,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 28.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=21, hours=8),
                'end_date': base_date + timedelta(days=21, hours=14),
                'requirements': 'İdman ayaqqabısı, rahat geyim',
                'what_included': 'Nəqliyyat, bələdçi',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'
            },
            {
                'title': 'Kino Gecəsi',
                'category': 'entertainment',
                'short_description': 'Açıq hava kino gecəsi',
                'description': 'Dənizkənarı parkda açıq hava kino gecəsi. Popkorn və əyləncəli vaxt.',
                'location_name': 'Dənizkənarı Park',
                'address': 'Dənizkənarı Milli Park',
                'district': 'sabail',
                'max_participants': 50,
                'min_participants': 20,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=7, hours=20),
                'end_date': base_date + timedelta(days=7, hours=23),
                'requirements': 'Battaniyə (seçim)',
                'what_included': 'Popkorn, içkilər',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800'
            },
            {
                'title': 'Mobil Tətbiq İnkişafı',
                'category': 'technology',
                'short_description': 'Mobil tətbiq yaratmağı öyrənin',
                'description': 'React Native ilə mobil tətbiq yaratmağı öyrənəcəksiniz. Praktiki layihə.',
                'location_name': 'Texnologiya Mərkəzi',
                'address': 'Nəsimi rayonu, Texnologiya Mərkəzi',
                'district': 'nasimi',
                'max_participants': 15,
                'min_participants': 8,
                'duration_hours': 5,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 45.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=17, hours=10),
                'end_date': base_date + timedelta(days=17, hours=15),
                'requirements': 'Laptop, JavaScript bilikləri',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800'
            },
            {
                'title': 'Bakı Gecə Gəzintisi',
                'category': 'travel',
                'short_description': 'Bakının gecə görünüşünü kəşf edin',
                'description': 'Bakının ən gözəl yerlərini gecə gəzintisi. Flame Towers, Bulvar və daha çox.',
                'location_name': 'Bakı Mərkəzi',
                'address': 'Flame Towers, Bakı',
                'district': 'sabail',
                'max_participants': 18,
                'min_participants': 8,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=22, hours=19),
                'end_date': base_date + timedelta(days=22, hours=22),
                'requirements': 'Rahat ayaqqabı',
                'what_included': 'Bələdçi, nəqliyyat',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800'
            },
            {
                'title': 'Basketbol Oyunu',
                'category': 'sports',
                'short_description': 'Basketbol meydanında oyun',
                'description': 'Basketbol meydanında dostlarla oyun. Hər səviyyədən oyunçu.',
                'location_name': 'İdman Kompleksi',
                'address': 'Nizami rayonu, İdman Kompleksi',
                'district': 'nizami',
                'max_participants': 16,
                'min_participants': 8,
                'duration_hours': 2,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 10.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=18, hours=17),
                'end_date': base_date + timedelta(days=18, hours=19),
                'requirements': 'İdman ayaqqabısı',
                'what_included': 'Meydan, top',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800'
            },
            {
                'title': 'Kosmetika Atölyəsi',
                'category': 'art',
                'short_description': 'Təbii kosmetika hazırlamağı öyrənin',
                'description': 'Təbii kosmetika məhsulları hazırlamağı öyrənəcəksiniz. Kremlər, maskalar və daha çox.',
                'location_name': 'Sənət Mərkəzi',
                'address': 'Yasamal rayonu, Sənət Mərkəzi',
                'district': 'yasamal',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 22.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=19, hours=15),
                'end_date': base_date + timedelta(days=19, hours=18),
                'requirements': 'Heç nə',
                'what_included': 'Bütün materiallar',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800'
            },
            {
                'title': 'Pilates Dərsləri',
                'category': 'health',
                'short_description': 'Pilates ilə güclü və çevik bədən',
                'description': 'Pilates məşğələləri ilə bədəninizi gücləndirin və çevikliyi artırın.',
                'location_name': 'Fitness Mərkəzi',
                'address': 'Nərimanov rayonu, Fitness Mərkəzi',
                'district': 'narimanov',
                'max_participants': 12,
                'min_participants': 5,
                'duration_hours': 1,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 18.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=12, hours=19),
                'end_date': base_date + timedelta(days=12, hours=20),
                'requirements': 'Rahat geyim',
                'what_included': 'Mat, su',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800'
            },
            {
                'title': 'Bakıxanov Turu',
                'category': 'travel',
                'short_description': 'Bakıxanovun tarixi yerlərinə ekskursiya',
                'description': 'Bakıxanovun tarixi yerlərinə ekskursiya. Qədim məscidlər və məzarlar.',
                'location_name': 'Bakıxanov',
                'address': 'Bakıxanov qəsəbəsi',
                'district': 'other',
                'max_participants': 15,
                'min_participants': 6,
                'duration_hours': 5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 22.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=20, hours=9),
                'end_date': base_date + timedelta(days=20, hours=14),
                'requirements': 'Rahat geyim',
                'what_included': 'Nəqliyyat, bələdçi',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'
            },
            {
                'title': 'Escape Room',
                'category': 'entertainment',
                'short_description': 'Escape room oyunu',
                'description': 'Dostlarla birlikdə escape room oyunu. Tapmacalar və tapşırıqlar.',
                'location_name': 'Escape Room',
                'address': 'Nizami rayonu, Escape Room',
                'district': 'nizami',
                'max_participants': 8,
                'min_participants': 4,
                'duration_hours': 1.5,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 25.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=14, hours=19),
                'end_date': base_date + timedelta(days=14, hours=20, minutes=30),
                'requirements': 'Heç nə',
                'what_included': 'Oyun, təlimat',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800'
            },
            {
                'title': 'Klassik Musiqi Konserti',
                'category': 'music',
                'short_description': 'Klassik musiqinin gözəl nümunələri',
                'description': 'Azərbaycan Dövlət Filarmoniyasında klassik musiqinin gözəl nümunələri.',
                'location_name': 'Filarmoniya',
                'address': 'Nizami prospekti, Filarmoniya',
                'district': 'nizami',
                'max_participants': 40,
                'min_participants': 15,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=23, hours=19),
                'end_date': base_date + timedelta(days=23, hours=21),
                'requirements': 'Heç nə',
                'what_included': 'Bilet',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'
            },
            {
                'title': 'Voleybol Oyunu',
                'category': 'sports',
                'short_description': 'Plaj voleybolu oyunu',
                'description': 'Çimərlikdə plaj voleybolu oyunu. Günəş, su və idman.',
                'location_name': 'Çimərlik',
                'address': 'Bilgəh çimərliyi',
                'district': 'khazar',
                'max_participants': 12,
                'min_participants': 6,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 12.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=24, hours=16),
                'end_date': base_date + timedelta(days=24, hours=18),
                'requirements': 'Çimərlik geyimi',
                'what_included': 'Top, meydan',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800'
            },
            {
                'title': 'Şokolad Hazırlama',
                'category': 'food',
                'short_description': 'Şokolad hazırlamağı öyrənin',
                'description': 'Şokolad hazırlama texnikalarını öyrənəcəksiniz. Öz şokoladınızı yaradın.',
                'location_name': 'Kulinariya Məktəbi',
                'address': 'Yasamal rayonu, Kulinariya Məktəbi',
                'district': 'yasamal',
                'max_participants': 10,
                'min_participants': 5,
                'duration_hours': 2.5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 28.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=21, hours=15),
                'end_date': base_date + timedelta(days=21, hours=17, minutes=30),
                'requirements': 'Apron',
                'what_included': 'Bütün materiallar, şokolad',
                'contact_phone': '+994 50 234 56 78',
                'image_url': 'https://images.unsplash.com/photo-1606312619070-d48b4e001599?w=800'
            },
            {
                'title': 'Günəş Doğuşu Meditasiyası',
                'category': 'health',
                'short_description': 'Günəş doğuşu ilə meditasiya',
                'description': 'Dənizkənarı parkda günəş doğuşu ilə meditasiya. Sülh və sakitlik.',
                'location_name': 'Dənizkənarı Park',
                'address': 'Dənizkənarı Milli Park',
                'district': 'sabail',
                'max_participants': 15,
                'min_participants': 5,
                'duration_hours': 1.5,
                'difficulty_level': 'beginner',
                'is_free': True,
                'price': 0.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=25, hours=6),
                'end_date': base_date + timedelta(days=25, hours=7, minutes=30),
                'requirements': 'Rahat geyim',
                'what_included': 'Mat, çay',
                'contact_phone': '+994 50 345 67 89',
                'image_url': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800'
            },
            {
                'title': 'Kifayətçilik İnkişafı',
                'category': 'education',
                'short_description': 'Şəxsi inkişaf və kifayətçilik',
                'description': 'Şəxsi inkişaf və kifayətçilik üzrə workshop. Məqsəd qoyma və nailiyyət.',
                'location_name': 'Təhsil Mərkəzi',
                'address': 'Nəsimi rayonu, Təhsil Mərkəzi',
                'district': 'nasimi',
                'max_participants': 20,
                'min_participants': 10,
                'duration_hours': 3,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 20.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=22, hours=14),
                'end_date': base_date + timedelta(days=22, hours=17),
                'requirements': 'Dəftər, qələm',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 456 78 90',
                'image_url': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800'
            },
            {
                'title': 'Su Şahidi Gəzintisi',
                'category': 'nature',
                'short_description': 'Su şahidinin gözəl təbiətini kəşf edin',
                'description': 'Su şahidinin gözəl təbiətini kəşf edin. Göl, meşə və gözəl mənzərələr.',
                'location_name': 'Su Şahidi',
                'address': 'Su Şahidi Milli Parkı',
                'district': 'other',
                'max_participants': 14,
                'min_participants': 6,
                'duration_hours': 7,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 30.00,
                'is_featured': True,
                'start_date': base_date + timedelta(days=26, hours=8),
                'end_date': base_date + timedelta(days=26, hours=15),
                'requirements': 'Rahat geyim, idman ayaqqabısı',
                'what_included': 'Nəqliyyat, bələdçi, nahar',
                'contact_phone': '+994 50 567 89 01',
                'image_url': 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800'
            },
            {
                'title': '3D Animasiya',
                'category': 'technology',
                'short_description': '3D animasiya yaratmağı öyrənin',
                'description': 'Blender ilə 3D animasiya yaratmağı öyrənəcəksiniz. Model və animasiya.',
                'location_name': 'Animasiya Mərkəzi',
                'address': 'Nəsimi rayonu, Animasiya Mərkəzi',
                'district': 'nasimi',
                'max_participants': 12,
                'min_participants': 6,
                'duration_hours': 4,
                'difficulty_level': 'intermediate',
                'is_free': False,
                'price': 38.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=23, hours=14),
                'end_date': base_date + timedelta(days=23, hours=18),
                'requirements': 'Laptop',
                'what_included': 'Materiallar, çay',
                'contact_phone': '+994 50 678 90 12',
                'image_url': 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=800'
            },
            {
                'title': 'Kənd Turu',
                'category': 'travel',
                'short_description': 'Azərbaycan kəndlərini kəşf edin',
                'description': 'Azərbaycan kəndlərinə günlük tur. Ənənəvi həyat tərzi və mətbəx.',
                'location_name': 'Lahıc',
                'address': 'Lahıc kəndi',
                'district': 'other',
                'max_participants': 16,
                'min_participants': 8,
                'duration_hours': 9,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 32.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=27, hours=7),
                'end_date': base_date + timedelta(days=27, hours=16),
                'requirements': 'Rahat geyim',
                'what_included': 'Nəqliyyat, bələdçi, nahar',
                'contact_phone': '+994 50 789 01 23',
                'image_url': 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800'
            },
            {
                'title': 'Masa Tenisi',
                'category': 'sports',
                'short_description': 'Masa tenisi oyunu',
                'description': 'Masa tenisi meydanında oyun və məşq. Hər səviyyədən oyunçu.',
                'location_name': 'İdman Kompleksi',
                'address': 'Nizami rayonu, İdman Kompleksi',
                'district': 'nizami',
                'max_participants': 8,
                'min_participants': 4,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 12.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=24, hours=18),
                'end_date': base_date + timedelta(days=24, hours=20),
                'requirements': 'İdman geyimi',
                'what_included': 'Masa, raket və top',
                'contact_phone': '+994 50 890 12 34',
                'image_url': 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=800'
            },
            {
                'title': 'Özəl Fotoqrafiya Sesiyası',
                'category': 'photography',
                'short_description': 'Professional fotoqrafiya sesiyası',
                'description': 'Professional fotoqraf rəhbərliyində özəl fotoqrafiya sesiyası. Portret və mənzərə.',
                'location_name': 'Foto Studio',
                'address': 'Yasamal rayonu, Foto Studio',
                'district': 'yasamal',
                'max_participants': 6,
                'min_participants': 2,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 35.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=28, hours=15),
                'end_date': base_date + timedelta(days=28, hours=17),
                'requirements': 'Heç nə',
                'what_included': 'Studio, avadanlıq, redaktə',
                'contact_phone': '+994 50 901 23 45',
                'image_url': 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800'
            },
            {
                'title': 'Azərbaycan Rəqsləri',
                'category': 'culture',
                'short_description': 'Azərbaycan xalq rəqslərini öyrənin',
                'description': 'Azərbaycan xalq rəqslərini öyrənəcəksiniz. Təcrübəli xoreoqraf rəhbərliyi.',
                'location_name': 'Rəqs Məktəbi',
                'address': 'Nizami prospekti, Rəqs Məktəbi',
                'district': 'nizami',
                'max_participants': 15,
                'min_participants': 8,
                'duration_hours': 2,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 18.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=25, hours=18),
                'end_date': base_date + timedelta(days=25, hours=20),
                'requirements': 'Rahat geyim',
                'what_included': 'Təlimat',
                'contact_phone': '+994 50 012 34 56',
                'image_url': 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800'
            },
            {
                'title': 'Yeni İlə Hazırlıq',
                'category': 'social',
                'short_description': 'Yeni ilə hazırlıq görüşü',
                'description': 'Yeni ilə hazırlıq görüşü. Birlikdə planlar hazırlayaq və əylənək.',
                'location_name': 'Kafe',
                'address': 'Nizami rayonu, Kafe',
                'district': 'nizami',
                'max_participants': 20,
                'min_participants': 10,
                'duration_hours': 2.5,
                'difficulty_level': 'beginner',
                'is_free': False,
                'price': 15.00,
                'is_featured': False,
                'start_date': base_date + timedelta(days=29, hours=18),
                'end_date': base_date + timedelta(days=29, hours=20, minutes=30),
                'requirements': 'Heç nə',
                'what_included': 'Çay, şirniyyat',
                'contact_phone': '+994 50 123 45 67',
                'image_url': 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800'
            }
        ]

        for activity_data in activities_data:
            category = categories[activity_data.pop('category')]
            image_url = activity_data.pop('image_url', None)
            activity_data['category'] = category
            activity_data['organizer'] = organizer
            activity_data['status'] = 'published'
            
            activity, created = Activity.objects.get_or_create(
                title=activity_data['title'],
                defaults=activity_data
            )
            
            if created:
                # Download and save image if URL provided
                if image_url:
                    try:
                        image_name = f"activity_{activity.id}.jpg"
                        image_path = os.path.join(settings.MEDIA_ROOT, 'activities', 'images', image_name)
                        os.makedirs(os.path.dirname(image_path), exist_ok=True)
                        
                        if self.download_image(image_url, image_path):
                            with open(image_path, 'rb') as f:
                                activity.main_image.save(image_name, File(f), save=True)
                            activity.image_alt = activity.title
                            activity.save()
                            self.stdout.write(f'Created activity with image: {activity.title}')
                        else:
                            self.stdout.write(f'Created activity (image download failed): {activity.title}')
                    except Exception as e:
                        self.stdout.write(self.style.WARNING(f'Could not set image for {activity.title}: {e}'))
                        self.stdout.write(f'Created activity: {activity.title}')
                else:
                    self.stdout.write(f'Created activity: {activity.title}')

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created sample data with {len(categories_data)} categories and {len(activities_data)} activities!')
        )
